### ISSUE TITLE
NPE w/ Grimpack Gravestone

### ISSUE THREAD

**Issue by WenXin20** [Stormwind99/DaringDebug#1]
Forge v14.23.4.2707-1.12.2
Daring Debug v2.0.0
[Open Blocks](https://minecraft.curseforge.com/projects/openblocks?gameCategorySlug=mc-mods&projectID=228816) v1.7.6

I got this NPE after pressing F3 while looking at the Open Blocks Gravestone. No crash log was created, it only disconnected me from the game.
[Log](https://gist.github.com/WenXin20/87e8dda6fd7569afc01ecd265a136436)

**Comment by Stormwind99** [comment]
I can't reproduce the crash - can you?

Screenshot of not crashing:
![2018-07-20_07 32 59](https://user-images.githubusercontent.com/9441438/43002739-7aef5472-8bef-11e8-80ad-5fb732ef1109.png)

**Comment by Stormwind99** [comment]
Give version 2.0.1 a try - see if it avoids the crash.

I suspect it was one of the other installed mods doing something improper, but don't see evidence of which mod in the log.

**Comment by WenXin20** [comment]
Ok, thanks, I was wondering why a grave formed despite having it disabled in Open Blocks. It looks like it was actually the Grimpack mod grave.

**Comment by Stormwind99** [comment]
Does it still crash with Daring Debug 2.0.1 or newer?

**Comment by WenXin20** [comment]
It works with the newer version.

**Comment by Stormwind99** [comment]
Great!
